name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build -t abdullahumar/java_maven_app_cicd .

    - name: Log into Dockerhub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASS }}

    - name: Push image to Dockerhub
      run: docker push abdullahumar/java_maven_app_cicd
